### ISSUE TITLE
The chart is incorrect!

### ISSUE THREAD

**Issue by aulorbe** [learn-co-curriculum/dsc-0-10-08-coefficient-of-determination#1]
The "Assessing Goodness of Fit" chart is wrong. It uses incorrect labels in the formulas, which is completely detrimental to our education. Please be more conscious of the material you put into this course.

SSE should be (Actual-Estimated), and there shouldn't be 1 label that refers to the actual value as "Actual" and another label that refers to the actual value as "Real."

**Comment by ShakeelRaja** [comment]
updated chart
